# generated by zon2nix (https://github.com/Cloudef/zig2nix)

{
  linkFarm,
  runCommand,
  zig,
  name ? "zig-packages",
}:

let
  fetchZig =
    {
      name,
      url,
      hash,
    }:
    runCommand name
      {
        src = url;
        nativeBuildInputs = [ zig ];
        outputHash = hash;
        outputHashMode = "recursive";
      }
      ''
        hash="$(zig fetch --global-cache-dir "$TMPDIR" "${url}")"
        mv "$TMPDIR/p/$hash" "$out"
        chmod 755 "$out"
      '';
in
linkFarm name [
  {
    name = "toml-0.3.0-bV14BVqIAQANb68hDuVPZ72hrcIhT-fv_fcIbetQIAyg";
    path = fetchZig {
      name = "toml";
      url = "https://github.com/sam701/zig-toml/archive/24e0deeceaad1b7f1b12027ebae1c65ff1d86e33.tar.gz";
      hash = "sha256-I0RskGSY+Kwzb/uKGd+b+tMitdNzwpynFvDh/GI8LZ0=";
    };
  }
]
