keys:
  - &users:
    - &rodnelkes age1up85q70a3k7vtxk7g504pn5evxczvr39mwfl206ymmgydgewpygskaw987
  - &hosts:
    - &boobookeys age13fzyz0rxnv0qcdpg4erfjwgtz92xsxjpr6jhxfwl5lw2n9aqquqsjfvqkm
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *rodnelkes
        - *boobookeys
